-- AlterTable
ALTER TABLE "Loan" ALTER COLUMN "loan_amount" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "interest_rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "monthly_payment" SET DATA TYPE DECIMAL(65,30);
